on: [push]

jobs:
  test_neovim:
    runs-on: ubuntu-latest
    name: A job to test spack installation of neovim
    steps:
    - name: Install step
      id: install
      uses: hhoeflin/spack-containers/spack-test-action
      with:
        spec: 'Mona the Octocat'
