on: [push]

jobs:
  test_neovim:
    runs-on: ubuntu-latest
    name: A job to test spack installation of neovim
    steps:
    - name: Install step
      id: install
      uses: hhoeflin/spack-containers/spack-test-action@master
      with:
        spec: ${{matrix.spec}}
    strategy:
      matrix:
        spec: [neovim@0.2.0, neovim@0.3.0, neovim@0.4.3, neovim@0.4.4, neovim@master, neovim@stable]
